sudo: false
language: php
php:
  - 7.0
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  # Remove xdebug to speed up composer
  - phpenv config-rm xdebug.ini

install:
- composer install --prefer-dist

script:
- php vendor/bin/phpcs --standard=PSR2 Api/ Block/ Controller/ Helper/ Model/ Observer/ Plugin/ Setup/ Test/ Ui/
#- php vendor/bin/phpmd Block/,Helper/,Model/,Observer/,Test/ text cleancode,codesize,controversial,design,naming,unusedcode