sudo: false
language: php
php:
  - 7.0
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_install:
  - phpenv config-rm xdebug.ini
install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install --prefer-dist
script:
  - php vendor/bin/phpcs . --standard=MEQP2
  #- php vendor/bin/phpmd Api/,Block/,Controller/,Model/,Observer/,Plugin/,Setup/,Test/,Ui/ text cleancode,codesize,controversial,design,naming,unusedcode
env:
  global:
  - secure: JMBNvdMr4djn+rgdpEeTcFfauAvWkfBadQehuP2CqUvnsPRbNSOzKbJ311yw0LHb94/uYl9PH/DEZO/1fnfZhZ1/rSmeURzQV+0aja7YKh4lOXh8pNW/X9wOuPLA91BQ2a4N03UZWVCXaornH183PbEKdg7RjcF28UL3Yljq14DYMX+LeW3JAJhoTi5IC8gDrwES7xyxVz/7M0SbyG1/Oy+ju75NNICceshPcMQMT3vuS7OL1i/jWvlPIJ5eksAgSZvjO+zs0EusvCasAG89bkLLrZcqTBb2m8IqsyNWQm2Gd5V1EpeHE7wOPwEOm48ZQBusws2ohOaegoJf7ctnuYjvnR2sQbnvidNQQcbtpfHfCQuBzvJI74zD6BEcSL20TKkiE0s2gcAu5ackYEcS3u5s6dVvbZj+Im288OZ4CHbrGXBlZIoKxCpxgL58q8KNkWKL+eE/HyZ8vEG6dzlO6lR2bpvpxopbsx9A4dCdTJi8nfXiNGRQ+TIYa6eKah90kpqAtu3rXRmsMMy3+TV9510rnMZfNPU02uoS0GVC4iP+jV0dEOFjDpYR2VQvC0ryZ/TMV724DLi7HfnwIhxHl1Mtu3C1i7WA5u5PzDBKBC4ucPL/jT5NrBzHQ1oeldkxh4Y7NlaD3fTVlY9MxvnZtvG3gnlyWbs10lhwuMBJlAA=
  - secure: dPJwkpj+hLBDFmk3YMAnjFWqGwTKK/71QUT4omHf8wqF+OdiZWIU74O0NdS3ddSLuQgx1049QtQ9r89dF0MxeJ+qqpq67UsTupBuweXhxQmiKAcHkGkzsvr8EDriBJFA8RnokyVf8xkpnTy/cb1W3b3J/lQc9HgtMplfrY4lul1GODZ8CXywbC7MAZZVpjU9yzqlY3WpMSX0e2HZ2FTJBP3vf3krECPAQKD1/7UDtQ3iIHV+Hymu8lHOsKDl9Fpz/URbuCFrwa1XOosWQhmo5neWHqFAzPRcxNOePJBRCAhzVRasI4Ym+vidXyOUsE4OZsGm3WGYKNsMMH/igy0OhI/ivNlm6Y3cs9FavnnMz1S7QnoUzFaxYDanTWd7Zyt80KURoefuVqm64IpQpxZcnIhuIMOaa6wbFeAY0eh5g2C/XDnDPb1J8JYLf9xsN1wA2VAs7NfBIShPLdR9es114lVHol2k9zePQoF14cJpT1YYj6ZhQH4fV4yeoJUDiA5pJNZBsaSTpGWLuBXkKR3Nn7oBvjRv0XMb06Y2PxHnf8R6rKX4VXMMiXagNil1pewS3TiTjUqhcAHIv5iDjYg4W61mzzizBHfFSC5nPTMqWvi84uYomjOcK5rOubH38Cb+pCkOQiRq8LA5UfgAMo8cOYoNfUYGLtX9KbrCwy9eB5A=
