<?php
/** @var \Netzexpert\ProductConfigurator\Block\Product\View\ConfiguratorOptions\Type\Expression $block */
$option = $block->getOption();
$_productId = $block->getProduct()->getId();
$isHidden = !$option->getIsVisible() ? ' hide' : '';
?>
<div id="option-<?php echo $option->getId() ?>" class="field<?php echo /* @escapeNotVerified */ $isHidden; ?>">
    <input type="text"
           id="expression-<?php echo /* @escapeNotVerified */ $option->getId() ?>"
           class="input-text product-configurator-option expression-value"
           name="configurator_options[<?php echo /* @escapeNotVerified */ $option->getId() ?>]"
           data-selector="configurator_options[<?= /* @escapeNotVerified */ $option->getId() ?>]"
           data-code="<?php echo /* @escapeNotVerified */ $option->getCode() ?>"
           value=""
           disabled="disabled" />
    <div class="label" >
        <span><?php echo /*$block->escapeHtml(*/$option->getName()/*)*/ ?></span>
    </div>
    <div class="option-value" id="option-value-<?php echo $option->getId() ?>">
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#option-<?php echo $option->getId() ?>": {
            "expressionField": {
                "input": "expression-<?php echo $option->getId(); ?>",
                "priceHolderSelector": "[data-product-id='<?= $block->escapeHtml($_productId) ?>'][data-role=priceBox]",
                "dependencyConfig": <?php echo /* @escapeNotVerified */ $block->getDependencyJsonConfig() ?>,
                "expressionCode": "<?php echo str_replace(array("\n", "\r"), '', $option->getData('expression'))?>",
                "optionCode": "<?= $option->getData('code') ?>"
            }
        }
    }
</script>