<?php
/** @var \Netzexpert\ProductConfigurator\Block\Product\View\ConfiguratorOptions\Type\Image $block */
$option = $block->getOption();
$required = $option->getData('is_required') ? ' required' : '';
$parentOptionDefaultValues = $this->getParentOptionDefaultValues();
$isHidden = !$block->getAvailableOptionsCount() || !$option->getIsVisible() ? ' hidden' : '';
$defaultValue = $block->getDefaultValue();
$value = null;
$disabled = false;
$magnifier = ($option->getData('use_magnifier')) ? ' easyzoom easyzoom--adjacent' : '';
?>
<div id="option-<?php echo $option->getId() ?>" class="field<?php echo /* @escapeNotVerified */ $required . $isHidden; ?>">
    <label class="label"><?php echo /* @escapeNotVerified */ $option->getData('name') ?></label>
    <div class="description">
        <?php echo /* @escapeNotVerified */ $block->getOptionDescription() ?>
    </div>
    <ul class="values">
        <?php
        $valuesData = $block->getValuesData();
        foreach ($valuesData as $item) {
            $disabled = false;
            if ($item['enabled']) {
                if ($item['value_id'] == $defaultValue) {
                    $value = $item['value'];
                }
                $selected = ($item['value_id'] == $defaultValue) ? ' selected' : '';
                $hidden = $disabled ? ' hide' : ''; ?>
                <li class="value<?php echo /* @escapeNotVerified */ $selected . $hidden . $magnifier; ?>"
                    id="value-<?php echo $item['value_id']; ?>"
                    data-value="<?php echo $item['value'] ?>"
                    data-id="<?php echo $item['value_id'] ?>">
                    <?php
                        if ($magnifier) {
                            ?>
                    <a href="<?php echo /* @escapeNotVerified */ $block->getImageUrl($item['image']) ?>">
                        <img src="<?php echo $block->getResizedImage($item, 135) ?>"
                             alt="<?php echo /* @escapeNotVerified */ $item['title']; ?>"
                             title="<?php echo /* @escapeNotVerified */ $item['title']; ?>"/>
                    </a>
                    <?php
                        } else {
                            ?>
                            <img src="<?php echo $block->getResizedImage($item, 135) ?>"
                                 alt="<?php echo /* @escapeNotVerified */ $item['title']; ?>"
                                 title="<?php echo /* @escapeNotVerified */ $item['title']; ?>"/>
                    <?php
                        } ?>
                </li>
                <?php
            }
        }
        ?>
    </ul>
    <div class="control">
        <select id="image-<?php echo /* @escapeNotVerified */ $option->getData('code') ?>"
                name="configurator_options[<?= /* @escapeNotVerified */ $option->getId() ?>]"
                class="product-configurator-option admin__control-select hide<?php echo /* @escapeNotVerified */ $required; ?>"
                data-selector="configurator_options[<?php echo /* @escapeNotVerified */ $option->getId() ?>]"
                data-code="<?php echo /* @escapeNotVerified */ $option->getCode() ?>">
            <option value><?php echo /* @escapeNotVerified */ __('-- Please Select --') ?></option>
            <?php
            foreach ($valuesData as $item) {
                $disabled = false;
                if ($item['is_dependent'] && !$block->isAllowed($parentOptionDefaultValues, $item['dependencies'])) {
                    $disabled = true;
                }
                if ($item['value_id'] == $defaultValue) {
                    $value = $item['value'];
                }
                $selected = (($item['value_id'] == $defaultValue) && !$disabled) ? ' selected="selected"' : ''; ?>
                <option data-id="value-<?php echo $item['value_id'] ?>"
                        value="<?php echo $item['value_id'] ?>"
                    <?php echo /* @escapeNotVerified */$selected ?>><?php echo /* @escapeNotVerified */ $item['title']; ?></option>
                <?php
            }
            ?>
        </select>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#option-<?php echo $option->getId() ?>": {
            "imageField": {
                "select": "image-<?php echo $option->getData('code') ?>"
            }
        }
    }
</script>
<script>
    require([
        'jquery',
        'easyZoom'
    ], function($){
        $(document).ready(function () {
            $('.easyzoom').easyZoom();
        })
    });
</script>