<?php
/** @var \Netzexpert\ProductConfigurator\Block\Product\View\ConfiguratorOptions\Type\Image $block */
$option = $block->getOption();
$required = $option->getData('is_required') ? ' required' : '';
$parentOptionDefaultValue = $this->getParentOptionDefaultValue();
$isHidden = !$block->getAvailableOptionsCount() || !$option->getIsVisible() ? ' hidden' : '';
$value = null;
$disabled = false;
?>
<div id="option-<?php echo $option->getId() ?>" class="field<?php echo /* @escapeNotVerified */ $required . $isHidden; ?>">
    <label class="label"><?php echo /* @escapeNotVerified */ $option->getData('name') ?></label>
    <div class="description">
        <?php echo /* @escapeNotVerified */ $option->getData('description') ?>
    </div>
    <ul class="values">
        <?php
        $valuesData = $block->getValuesData();
        foreach ($valuesData as $item) {
            $disabled = false;
            if ($item['is_dependent'] && !in_array($parentOptionDefaultValue, $item['allowed_variants'])) {
                $disabled = true;
            }
            if ($item['enabled']) {
                if ($item['is_default']) {
                    $value = $item['value'];
                }
                $selected = $item['is_default'] ? ' selected' : '';
                $hidden = $disabled ? ' hide' : '';
                ?>
                <li class="value<?php echo /* @escapeNotVerified */ $selected . $hidden; ?>"
                    id="value-<?php echo $item['value_id']; ?>"
                    data-value="<?php echo $item['value'] ?>"
                    data-id="<?php echo $item['value_id'];?>">
                    <img src="<?php echo $block->getResizedImage($item, 135) ?>"
                         alt="<?php echo /* @escapeNotVerified */ $item['title']; ?>"
                         title="<?php echo /* @escapeNotVerified */ $item['title']; ?>"/>
                </li>
                <?php
            }
        }
        ?>
    </ul>
    <div class="control">
        <select id="image-<?php echo /* @escapeNotVerified */ $option->getData('code') ?>"
                name="configurator_options[<?php echo /* @escapeNotVerified */ $option->getId() ?>]"
                class="product-configurator-option admin__control-select hide<?php echo /* @escapeNotVerified */ $required; ?>"
                data-selector="configurator_options[<?php echo /* @escapeNotVerified */ $option->getId() ?>]"
                data-code="<? echo /* @escapeNotVerified */ $option->getCode() ?>">
            <option value><?php echo /* @escapeNotVerified */ __('-- Please Select --') ?></option>
            <?php
            foreach ($valuesData as $item) {
                $disabled = false;
                if ($item['is_dependent'] && !in_array($parentOptionDefaultValue, $item['allowed_variants'])) {
                    $disabled = true;
                }
                if ($item['is_default']) {
                    $value = $item['value'];
                }
                $selected = ($item['is_default'] && !$disabled) ? ' selected="selected"' : '';
                ?>
                <option data-id="value-<?php echo $item['value_id'];?>"
                        value="<?php echo $item['value_id'] ?>"
                    <?php echo /* @escapeNotVerified */$selected ?>><?php echo /* @escapeNotVerified */ $item['title']; ?></option>
                <?php
            }
            ?>
        </select>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#option-<?php echo $option->getId() ?>": {
            "imageField": {
            }
        }
    }
</script>