<?php
/** @var $block \Netzexpert\ProductConfigurator\Block\Product\View\SelectionWidget */
if ($block->isEnabled()) {
    ?>

    <div class="widget selected-options">
        <h3>Selected options</h3>
        <div data-role="selected-options" class="content">
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "[data-role=selected-options]": {
                "selectionWidget": {}
            }
        }
    </script>
<?php
}
?>