<?php
/** @var \Netzexpert\ProductConfigurator\Block\Product\View\Type\Configurator $block */
$product = $block->getProduct();
$optionsGroups = $block->getConfiguratorOptions();
$_productId = $product->getId();
if (!empty($optionsGroups)) :
?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "configuratorOptions": {
                    "optionConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                    "priceHolderSelector": "[data-product-id='<?= $block->escapeHtml($_productId) ?>'][data-role=priceBox]",
                    "dependencyConfig": <?php echo /* @escapeNotVerified */ $block->getDependencyJsonConfig() ?>
                },
                "configuratorValidation": {}
            }
        }
    </script>
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
        </div>
    </div>
<div id="configurator-options-accordion"
     data-sections="tabs">
<?php
foreach ($optionsGroups as $optionsGroup) {
    echo '<div class="item title" data-section="title" data-role="collapsible">
            <div class="switch" data-toggle="switch" data-role="trigger">' . $optionsGroup['group_name'] . '</div>
         </div>';
    echo '<div class="item content" data-role="content">';
    foreach ($optionsGroup['options'] as $option) {
        echo $block->getOptionHtml($option);
    }
    echo '</div>';
}
?>
    <input type="hidden" id="configured_price" value="" />
</div>
<script>
    require([
        'jquery',
        'accordion'
    ], function ($) {
        $("#configurator-options-accordion").accordion({
            "active": "0",
            "openedState": "active",
            "collapsible": true,
            "multipleCollapsible": true,
            "animate": {
                duration:300
            }
        });
    });
</script>
<?php
endif;
?>
